<Screen>:
    orientation: 'vertical'
    size_hint_y: None
    height: self.minimum_height
    size_hint_x: None
    width: 400

    canvas:
        Color:
            rgba: 1.0, 0.9451, 0.6588, 1.0
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: None
        height: 500

        BoxLayout:
            size_hint_x: None
            width: 40

            BoxLayout:
                size_hint_x: None
                width: 5
                canvas:
                    Color:
                        rgba: 0, 0, 0, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size

            Label:
                font_size: 20
                text: 'B\na\nc\na\nn\na\ns\n \nR\ne\ns\nt\na\nu\nr\na\nn\nt\ne'
                color: 0, 0, 0, 1

            BoxLayout:
                size_hint_x: None
                width: 5
                canvas:
                    Color:
                        rgba: 0, 0, 0, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size






        BoxLayout:
            orientation: 'vertical'
            size_hint_x: None
            width: 320

            Label:
                text: ''






        BoxLayout:
            size_hint_x: None
            width: 40

            BoxLayout:
                size_hint_x: None
                width: 5
                canvas:
                    Color:
                        rgba: 0, 0, 0, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size

            Label:
                font_size: 20
                text: 'B\na\nc\na\nn\na\ns\n \nR\ne\ns\nt\na\nu\nr\na\nn\nt\ne'
                color: 0, 0, 0, 1

            BoxLayout:
                size_hint_x: None
                width: 5
                canvas:
                    Color:
                        rgba: 0, 0, 0, 1
                    Rectangle:
                        pos: self.pos
                        size: self.size